sets.exported={
    main={ name="Vampirism", augments={'STR+10','INT+10','"Occult Acumen"+10','DMG:+15',}},
    sub="Ark Shield",
    range="Gjallarhorn",
    head="Inyanga Tiara +2",
    body="Inyanga Jubbah +2",
    hands="Inyan. Dastanas +2",
    legs="Aya. Cosciales +2",
    feet="Aya. Gambieras +1",
    neck="Elite Royal Collar",
    waist="Witful Belt",
    left_ear="Aoidos' Earring",
    right_ear="Loquac. Earring",
    left_ring="Inyanga Ring",
    right_ring="Stikini Ring",
    back="Swith Cape",
}