sets.exported={
    main="Chatoyant Staff",
    sub="Achaq Grip",
    ammo="Staunch Tathlum",
    head={ name="Vanya Hood", augments={'MP+50','"Fast Cast"+10','Haste+2%',}},
    body="Ebers Bliaut +1",
    hands="Theophany Mitts +2",
    legs="Ebers Pant. +1",
    feet="Regal Pumps +1",
    neck="Nodens Gorget",
    waist="Hachirin-no-Obi",
    left_ear="Nourish. Earring +1",
    right_ear="Mendi. Earring",
    left_ring="Stikini Ring",
    right_ring="Janniston Ring",
    back="Tempered Cape +1",
}