sets.exported={
    main="Daybreak",
    sub="Sors Shield",
    ammo="Staunch Tathlum",
    head="Inyanga Tiara +1",
    body="Inyanga Jubbah +2",
    hands="Inyan. Dastanas +1",
    legs="Assid. Pants +1",
    feet="Inyan. Crackows +1",
    neck="Nodens Gorget",
    waist="Austerity Belt",
    left_ear="Nourish. Earring +1",
    right_ear="Mendi. Earring",
    left_ring="Inyanga Ring",
    right_ring="Stikini Ring",
    back="Pahtli Cape",
}