sets.exported={
    main={ name="Solstice", augments={'Mag. Acc.+20','Pet: Damage taken -4%','"Fast Cast"+5',}},
    sub="Sors Shield",
    range={ name="Dunna", augments={'MP+20','Mag. Acc.+10','"Fast Cast"+3',}},
    head="Azimuth Hood +1",
    body="Geo. Tunic +1",
    hands="Geo. Mitaines +1",
    legs="Geo. Pants +1",
    feet="Geo. Sandals +1",
    neck={ name="Bagua Charm +1", augments={'Path: A',}},
    waist="Austerity Belt",
    left_ear="Mendi. Earring",
    right_ear="Gna Earring",
    left_ring="Stikini Ring",
    right_ring="Stikini Ring",
    back={ name="Lifestream Cape", augments={'Geomancy Skill +9','Indi. eff. dur. +20','Pet: Damage taken -5%',}},
}