sets.exported={
    main="Naegling",
    sub={ name="Fusetto +2", augments={'TP Bonus +1000',}},
    range={ name="Linos", augments={'Accuracy+15','"Store TP"+4','Quadruple Attack +3',}},
    head="Aya. Zucchetto +2",
    body="Ayanmo Corazza +2",
    hands="Aya. Manopolas +2",
    legs={ name="Telchine Braconi", augments={'Accuracy+15 Attack+15','"Store TP"+5','STR+7 DEX+7',}},
    feet="Battlecast Gaiters",
    neck={ name="Bard's Charm +1", augments={'Path: A',}},
    waist={ name="Sailfi Belt +1", augments={'Path: A',}},
    left_ear="Mache Earring",
    right_ear="Suppanomimi",
    left_ring="Chirich Ring",
    right_ring="Chirich Ring",
    back={ name="Intarabus's Cape", augments={'DEX+20','Accuracy+20 Attack+20','DEX+10','"Store TP"+10','Phys. dmg. taken-10%',}},
}