sets.exported={
    main="Daybreak",
    sub="Sors Shield",
    ammo="Impatiens",
    head={ name="Vanya Hood", augments={'MP+50','"Fast Cast"+10','Haste+2%',}},
    body="Ebers Bliaut +1",
    hands={ name="Fanatic Gloves", augments={'MP+45','Healing magic skill +9','"Conserve MP"+6','"Fast Cast"+5',}},
    legs="Theo. Pant. +1",
    feet={ name="Vanya Clogs", augments={'"Cure" potency +5%','"Cure" spellcasting time -15%','"Conserve MP"+6',}},
    neck="Malison Medallion",
    waist="Witful Belt",
    left_ear="Meili Earring",
    right_ear="Malignance Earring",
    left_ring="Haoma's Ring",
    right_ring="Haoma's Ring",
    back={ name="Mending Cape", augments={'Healing magic skill +8','Enha.mag. skill +10','Mag. Acc.+4',}},
}