sets.exported={
    main="Kaja Sword",
    sub="Ternion Dagger +1",
    range={ name="Linos", augments={'Accuracy+14','"Store TP"+3','Quadruple Attack +2',}},
    head="Aya. Zucchetto +2",
    body="Ayanmo Corazza +2",
    hands="Aya. Manopolas +2",
    legs="Aya. Cosciales +2",
    feet="Battlecast Gaiters",
    neck={ name="Bard's Charm +1", augments={'Path: A',}},
    waist="Sailfi Belt +1",
    left_ear="Eabani Earring",
    right_ear="Suppanomimi",
    left_ring="Rajas Ring",
    right_ring="Petrov Ring",
    back={ name="Intarabus's Cape", augments={'DEX+20','Accuracy+20 Attack+20','DEX+10','"Store TP"+10','Phys. dmg. taken-10%',}},
}