sets.exported={
    main="Daybreak",
    sub="Sors Shield",
    ammo="Impatiens",
    head={ name="Vanya Hood", augments={'MP+50','"Fast Cast"+10','Haste+2%',}},
    body="Ebers Bliaut +1",
    hands="Theophany Mitts +2",
    legs="Theo. Pant. +1",
    feet="Regal Pumps +1",
    neck="Malison Medallion",
    waist="Witful Belt",
    left_ear="Meili Earring",
    right_ear="Malignance Earring",
    left_ring="Haoma's Ring",
    right_ring="Haoma's Ring",
    back="Mending Cape",
}