sets.exported={
    main={ name="Kali", augments={'Mag. Acc.+15','String instrument skill +10','Wind instrument skill +10',}},
    sub="Ark Shield",
    range="Gjallarhorn",
    head="Brioso Roundlet +1",
    body="Inyanga Jubbah +2",
    hands="Fili Manchettes +1",
    legs="Brioso Cannions +2",
    feet="Aya. Gambieras +1",
    neck="Mnbw. Whistle +1",
    waist="Witful Belt",
    left_ear="Aoidos' Earring",
    right_ear="Loquac. Earring",
    left_ring="Stikini Ring",
    right_ring="Stikini Ring",
    back="Swith Cape",
}