sets.exported={
    main={ name="Rubicundity", augments={'Mag. Acc.+1','"Mag.Atk.Bns."+5','"Conserve MP"+1',}},
    sub="Genmei Shield",
    ammo="Pemphredo Tathlum",
    head={ name="Bagua Galero +1", augments={'Enhances "Primeval Zeal" effect',}},
    body="Geo. Tunic +1",
    hands={ name="Merlinic Dastanas", augments={'Mag. Acc.+10','"Drain" and "Aspir" potency +10','MND+6','"Mag.Atk.Bns."+10',}},
    legs="Azimuth Tights",
    feet="Geo. Sandals +1",
    neck="Deceiver's Torque",
    waist="Eschan Stone",
    left_ear="Malignance Earring",
    right_ear={ name="Azimuth Earring", augments={'System: 1 ID: 1676 Val: 0','Mag. Acc.+7',}},
    left_ring="Evanescence Ring",
    right_ring="Stikini Ring",
    back="Izdubar Mantle",
}