sets.exported={
    main={ name="Gada", augments={'"Fast Cast"+6','VIT+5','Mag. Acc.+19','DMG:+10',}},
    sub="Genmei Shield",
    range={ name="Dunna", augments={'MP+20','Mag. Acc.+10','"Fast Cast"+3',}},
    head={ name="Telchine Cap", augments={'Mag. Acc.+10','"Fast Cast"+5','Enh. Mag. eff. dur. +8',}},
    body={ name="Telchine Chas.", augments={'Mag. Evasion+5','Spell interruption rate down -9%','Enh. Mag. eff. dur. +10',}},
    hands={ name="Telchine Gloves", augments={'Mag. Evasion+17','Spell interruption rate down -7%','Enh. Mag. eff. dur. +10',}},
    legs={ name="Telchine Braconi", augments={'"Mag.Atk.Bns."+15','"Fast Cast"+4','Enh. Mag. eff. dur. +7',}},
    feet={ name="Telchine Pigaches", augments={'Mag. Acc.+5','"Cure" spellcasting time -4%','Enh. Mag. eff. dur. +7',}},
    neck="Incanter's Torque",
    waist="Olympus Sash",
    left_ear="Andoaa Earring",
    right_ear="Mimir Earring",
    left_ring="Stikini Ring",
    right_ring="Stikini Ring",
    back="Merciful Cape",
}