sets.exported={
    main="Daybreak",
    sub="Ammurapi Shield",
    ammo="Hydrocera",
    head={ name="Viti. Chapeau +1", augments={'Enfeebling Magic duration','Magic Accuracy',}},
    body="Lethargy Sayon +1",
    hands="Leth. Gantherots +1",
    legs="Leth. Fuseau +1",
    feet={ name="Vitiation Boots +2", augments={'Immunobreak Chance',}},
    neck={ name="Dls. Torque +2", augments={'Path: A',}},
    waist="Sacro Cord",
    left_ear="Regal Earring",
    right_ear="Snotra Earring",
    left_ring="Stikini Ring +1",
    right_ring="Stikini Ring +1",
    back={ name="Sucellos's Cape", augments={'MND+20','Mag. Acc+20 /Mag. Dmg.+20','"Fast Cast"+10','Damage taken-5%',}},
}