sets.exported={
    main="Bunzi's Rod",
    sub="Ammurapi Shield",
    ammo="Ghastly Tathlum +1",
    head="Agwu's Cap",
    body={ name="Bagua Tunic +3", augments={'Enhances "Bolster" effect',}},
    hands={ name="Bagua Mitaines +3", augments={'Enhances "Curative Recantation" effect',}},
    legs="Agwu's Slops",
    feet="Agwu's Pigaches",
    neck="Mizu. Kubikazari",
    waist="Sacro Cord",
    left_ear="Malignance Earring",
    right_ear="Regal Earring",
    left_ring="Freke Ring",
    right_ring="Metamor. Ring +1",
    back={ name="Nantosuelta's Cape", augments={'INT+20','Mag. Acc+20 /Mag. Dmg.+20','INT+8','"Mag.Atk.Bns."+10',}},
}