sets.exported={
    main="Caladbolg",
    sub="Utu Grip",
    ammo="Knobkierrie",
    head={ name="Odyssean Helm", augments={'Weapon skill damage +2%','VIT+10','Accuracy+8','Attack+13',}},
    body="Ignominy Cuirass +2",
    hands={ name="Odyssean Gauntlets", augments={'Weapon skill damage +2%','VIT+14','Accuracy+12','Attack+8',}},
    legs={ name="Fall. Flanchard +3", augments={'Enhances "Muted Soul" effect',}},
    feet="Sulev. Leggings +2",
    neck={ name="Abyssal Beads +1", augments={'Path: A',}},
    waist={ name="Sailfi Belt +1", augments={'Path: A',}},
    left_ear={ name="Moonshade Earring", augments={'Accuracy+4','TP Bonus +250',}},
    right_ear="Thrud Earring",
    left_ring="Regal Ring",
    right_ring="Niqmaddu Ring",
    back={ name="Ankou's Mantle", augments={'DEX+20','Accuracy+20 Attack+20','Accuracy+10','"Dbl.Atk."+10','Phys. dmg. taken-10%',}},
}