sets.exported={
    main="Daybreak",
    sub="Sacro Bulwark",
    ammo="Staunch Tathlum",
    head={ name="Nyame Helm", augments={'Path: B',}},
    body={ name="Viti. Tabard +2", augments={'Enhances "Chainspell" effect',}},
    hands={ name="Nyame Gauntlets", augments={'Path: B',}},
    legs={ name="Nyame Flanchard", augments={'Path: B',}},
    feet={ name="Nyame Sollerets", augments={'Path: B',}},
    neck={ name="Loricate Torque +1", augments={'Path: A',}},
    waist="Embla Sash",
    left_ear="Malignance Earring",
    right_ear={ name="Leth. Earring +1", augments={'System: 1 ID: 1676 Val: 0','Accuracy+13','Mag. Acc.+13','"Dbl.Atk."+4',}},
    left_ring="Kishar Ring",
    right_ring="Defending Ring",
    back={ name="Sucellos's Cape", augments={'MND+20','Mag. Acc+20 /Mag. Dmg.+20','MND+5','"Fast Cast"+10','Damage taken-5%',}},
}