sets.exported={
    main="Naegling",
    sub="Chanter's Shield",
    ammo="Homiliary",
    head={ name="Viti. Chapeau +1", augments={'Enfeebling Magic duration','Magic Accuracy',}},
    body="Shamash Robe",
    hands="Volte Gloves",
    legs="Bunzi's Pants",
    feet={ name="Merlinic Crackows", augments={'Mag. Acc.+3','"Conserve MP"+6','CHR+9',}},
    neck={ name="Loricate Torque +1", augments={'Path: A',}},
    waist="Flume Belt +1",
    left_ear={ name="Odnowa Earring +1", augments={'Path: A',}},
    right_ear="Etiolation Earring",
    left_ring={ name="Gelatinous Ring +1", augments={'Path: A',}},
    right_ring="Defending Ring",
    back="Moonbeam Cape",
}