sets.exported={
    main={ name="Epeolatry", augments={'Path: A',}},
    sub={ name="Refined Grip +1", augments={'Path: A',}},
    ammo="Sapience Orb",
    head="Rune. Bandeau +3",
    body="Erilaz Surcoat +2",
    hands="Agwu's Gages",
    legs="Eri. Leg Guards +2",
    feet="Erilaz Greaves +2",
    neck={ name="Futhark Torque +2", augments={'Path: A',}},
    waist="Flume Belt +1",
    left_ear={ name="Odnowa Earring +1", augments={'Path: A',}},
    right_ear="Loquac. Earring",
    left_ring="Moonlight Ring",
    right_ring="Defending Ring",
    back={ name="Ogma's Cape", augments={'HP+60','Eva.+20 /Mag. Eva.+20','HP+20','"Fast Cast"+10','Damage taken-4%',}},
}