sets.exported={
    main="Apocalypse",
    sub="Utu Grip",
    ammo="Staunch Tathlum",
    head="Ratri Sallet",
    body="Heath. Cuirass +1",
    hands="Sakpata's Gauntlets",
    legs="Ratri Cuisses",
    feet="Ratri Sollerets",
    neck={ name="Unmoving Collar +1", augments={'Path: A',}},
    waist="Eschan Stone",
    left_ear={ name="Odnowa Earring +1", augments={'Path: A',}},
    right_ear="Tuisto Earring",
    left_ring={ name="Gelatinous Ring +1", augments={'Path: A',}},
    right_ring="Moonbeam Ring",
    back="Moonbeam Cape",
}