sets.exported={
    main="Daybreak",
    sub="Ammurapi Shield",
    ammo="Hydrocera",
    head="Malignance Chapeau",
    body="Shamash Robe",
    hands="Regal Cuffs",
    legs="Malignance Tights",
    feet="Malignance Boots",
    neck="Incanter's Torque",
    waist="Sacro Cord",
    left_ear="Regal Earring",
    right_ear="Malignance Earring",
    left_ring={ name="Metamor. Ring +1", augments={'Path: A',}},
    right_ring="Stikini Ring",
    back={ name="Sucellos's Cape", augments={'MND+20','Mag. Acc+20 /Mag. Dmg.+20','"Fast Cast"+10','Damage taken-5%',}},
}