sets.exported={
    main="Daybreak",
    sub="Ammurapi Shield",
    ammo="Staunch Tathlum",
    head={ name="Telchine Cap", augments={'Mag. Acc.+10','"Fast Cast"+5','Enh. Mag. eff. dur. +9',}},
    body={ name="Viti. Tabard +2", augments={'Enhances "Chainspell" effect',}},
    hands="Atrophy Gloves +1",
    legs={ name="Telchine Braconi", augments={'"Mag.Atk.Bns."+15','"Fast Cast"+4','Enh. Mag. eff. dur. +9',}},
    feet="Leth. Houseaux +1",
    neck={ name="Dls. Torque +2", augments={'Path: A',}},
    waist="Embla Sash",
    left_ear="Malignance Earring",
    right_ear="Loquac. Earring",
    left_ring="Stikini Ring +1",
    right_ring="Kishar Ring",
    back={ name="Ghostfyre Cape", augments={'Enfb.mag. skill +5','Enha.mag. skill +2','Mag. Acc.+6','Enh. Mag. eff. dur. +18',}},
}