sets.exported={
    main={ name="Bunzi's Rod", augments={'Path: A',}},
    sub="Ammurapi Shield",
    ammo="Ghastly Tathlum +1",
    head="Ea Hat +1",
    body="Azimuth Coat +2",
    hands="Agwu's Gages",
    legs="Azimuth Tights +2",
    feet="Agwu's Pigaches",
    neck="Sibyl Scarf",
    waist="Sacro Cord",
    left_ear="Malignance Earring",
    right_ear="Regal Earring",
    left_ring="Freke Ring",
    right_ring={ name="Metamor. Ring +1", augments={'Path: A',}},
    back={ name="Nantosuelta's Cape", augments={'INT+20','Mag. Acc+20 /Mag. Dmg.+20','INT+8','"Mag.Atk.Bns."+10',}},
}