sets.exported={
    main={ name="Rubicundity", augments={'Mag. Acc.+5','"Mag.Atk.Bns."+3','Dark magic skill +8',}},
    sub="Ammurapi Shield",
    ammo="Pemphredo Tathlum",
    head={ name="Bagua Galero +3", augments={'Enhances "Primeval Zeal" effect',}},
    body="Geomancy Tunic +2",
    hands={ name="Merlinic Dastanas", augments={'"Drain" and "Aspir" potency +11','STR+2','"Mag.Atk.Bns."+13',}},
    legs="Geomancy Pants +3",
    feet="Agwu's Pigaches",
    neck="Erra Pendant",
    waist="Fucho-no-Obi",
    left_ear="Hirudinea Earring",
    right_ear="Regal Earring",
    left_ring="Evanescence Ring",
    right_ring={ name="Metamor. Ring +1", augments={'Path: A',}},
    back={ name="Nantosuelta's Cape", augments={'INT+20','Mag. Acc+20 /Mag. Dmg.+20','INT+8','"Mag.Atk.Bns."+10',}},
}