sets.exported={
    main="Caladbolg",
    sub="Utu Grip",
    ammo="Knobkierrie",
    head={ name="Odyssean Helm", augments={'Accuracy+24 Attack+24','Weapon Skill Acc.+5','VIT+14','Attack+8',}},
    body="Ignominy Cuirass +3",
    hands={ name="Odyssean Gauntlets", augments={'Accuracy+16 Attack+16','Weapon skill damage +2%','VIT+11','Accuracy+14',}},
    legs={ name="Fall. Flanchard +3", augments={'Enhances "Muted Soul" effect',}},
    feet="Sulev. Leggings +2",
    neck={ name="Abyssal Beads +1", augments={'Path: A',}},
    waist="Fotia Belt",
    left_ear={ name="Moonshade Earring", augments={'Accuracy+4','TP Bonus +250',}},
    right_ear="Thrud Earring",
    left_ring="Regal Ring",
    right_ring="Niqmaddu Ring",
    back={ name="Ankou's Mantle", augments={'VIT+20','Accuracy+20 Attack+20','VIT+10','Weapon skill damage +10%','Phys. dmg. taken-10%',}},
}