sets.exported={
    main="Epeolatry",
    sub={ name="Refined Grip +1", augments={'Path: A',}},
    ammo="Staunch Tathlum",
    head={ name="Fu. Bandeau +2", augments={'Enhances "Battuta" effect',}},
    body={ name="Taeon Tabard", augments={'Attack+23','"Dual Wield"+3','Phalanx +3',}},
    hands={ name="Taeon Gloves", augments={'Accuracy+18 Attack+18','"Dual Wield"+4','Phalanx +3',}},
    legs={ name="Taeon Tights", augments={'Accuracy+17 Attack+17','"Dual Wield"+3','Phalanx +3',}},
    feet={ name="Taeon Boots", augments={'Weapon Skill Acc.+20','Phalanx +3',}},
    neck="Incanter's Torque",
    waist="Olympus Sash",
    left_ear="Mimir Earring",
    right_ear={ name="Odnowa Earring +1", augments={'Path: A',}},
    left_ring={ name="Gelatinous Ring +1", augments={'Path: A',}},
    right_ring="Stikini Ring",
    back="Moonbeam Cape",
}