sets.exported={
    main="Bunzi's Rod",
    sub="Ammurapi Shield",
    range={ name="Dunna", augments={'MP+20','Mag. Acc.+10','"Fast Cast"+3',}},
    head="Agwu's Cap",
    body={ name="Bagua Tunic +3", augments={'Enhances "Bolster" effect',}},
    hands={ name="Bagua Mitaines +3", augments={'Enhances "Curative Recantation" effect',}},
    legs="Agwu's Slops",
    feet="Agwu's Pigaches",
    neck="Sanctity Necklace",
    waist="Sacro Cord",
    left_ear="Barkaro. Earring",
    right_ear="Regal Earring",
    left_ring="Freke Ring",
    right_ring="Stikini Ring",
    back="Izdubar Mantle",
}