sets.exported={
    main="Caladbolg",
    sub="Utu Grip",
    ammo={ name="Seeth. Bomblet +1", augments={'Path: A',}},
    head="Ratri Sallet",
    body="Ignominy Cuirass +3",
    hands="Rat. Gadlings +1",
    legs={ name="Fall. Flanchard +3", augments={'Enhances "Muted Soul" effect',}},
    feet="Sulev. Leggings +2",
    neck={ name="Abyssal Beads +1", augments={'Path: A',}},
    waist={ name="Sailfi Belt +1", augments={'Path: A',}},
    left_ear={ name="Lugra Earring +1", augments={'Path: A',}},
    right_ear="Thrud Earring",
    left_ring="Epaminondas's Ring",
    right_ring="Niqmaddu Ring",
    back={ name="Ankou's Mantle", augments={'STR+20','Accuracy+20 Attack+20','STR+10','Weapon skill damage +10%',}},
}