sets.exported={
    main={ name="Epeolatry", augments={'Path: A',}},
    sub="Utu Grip",
    ammo={ name="Seeth. Bomblet +1", augments={'Path: A',}},
    head="Agwu's Cap",
    body="Agwu's Robe",
    hands="Agwu's Gages",
    legs="Agwu's Slops",
    feet={ name="Agwu's Pigaches", augments={'Path: A',}},
    neck="Sibyl Scarf",
    waist="Eschan Stone",
    left_ear={ name="Odnowa Earring +1", augments={'Path: A',}},
    right_ear="Friomisi Earring",
    left_ring="Mujin Band",
    right_ring="Locus Ring",
    back="Izdubar Mantle",
}