sets.exported={
    main="Epeolatry",
    sub="Utu Grip",
    ammo="Staunch Tathlum",
    head="Rune. Bandeau +3",
    body={ name="Taeon Tabard", augments={'Spell interruption rate down -9%','"Regen" potency+2',}},
    hands="Regal Gauntlets",
    legs={ name="Futhark Trousers +3", augments={'Enhances "Inspire" effect',}},
    feet={ name="Taeon Boots", augments={'Spell interruption rate down -10%','"Regen" potency+2',}},
    neck={ name="Futhark Torque +1", augments={'Path: A',}},
    waist="Olympus Sash",
    left_ear={ name="Odnowa Earring +1", augments={'Path: A',}},
    right_ear="Etiolation Earring",
    left_ring={ name="Gelatinous Ring +1", augments={'Path: A',}},
    right_ring="Defending Ring",
    back={ name="Ogma's Cape", augments={'HP+60','Eva.+20 /Mag. Eva.+20','HP+20','"Fast Cast"+10',}},
}