sets.exported={
    main={ name="Grioavolr", augments={'Enfb.mag. skill +10','MND+12','Mag. Acc.+22','Magic Damage +2',}},
    sub="Enki Strap",
    ammo="Hydrocera",
    head="Geo. Galero +2",
    body="Agwu's Robe",
    hands="Regal Cuffs",
    legs="Geomancy Pants +3",
    feet="Geo. Sandals +3",
    neck="Erra Pendant",
    waist="Sacro Cord",
    left_ear="Malignance Earring",
    right_ear="Regal Earring",
    left_ring="Kishar Ring",
    right_ring="Freke Ring",
    back={ name="Nantosuelta's Cape", augments={'INT+20','Mag. Acc+20 /Mag. Dmg.+20','INT+8','"Mag.Atk.Bns."+10',}},
}