sets.exported={
    main={ name="Grioavolr", augments={'Enfb.mag. skill +10','MND+12','Mag. Acc.+22','Magic Damage +2',}},
    sub="Enki Strap",
    ammo="Pemphredo Tathlum",
    head="Geo. Galero +2",
    body="Geomancy Tunic +2",
    hands="Azimuth Gloves +2",
    legs="Geomancy Pants +3",
    feet="Geo. Sandals +3",
    neck={ name="Bagua Charm +1", augments={'Path: A',}},
    waist="Sacro Cord",
    left_ear="Malignance Earring",
    right_ear="Regal Earring",
    left_ring="Kishar Ring",
    right_ring={ name="Metamor. Ring +1", augments={'Path: A',}},
    back={ name="Nantosuelta's Cape", augments={'INT+20','Mag. Acc+20 /Mag. Dmg.+20','INT+8','"Mag.Atk.Bns."+10',}},
}