sets.exported={
    main={ name="Epeolatry", augments={'Path: A',}},
    sub="Utu Grip",
    ammo="Sapience Orb",
    head={ name="Nyame Helm", augments={'Path: B',}},
    body={ name="Nyame Mail", augments={'Path: B',}},
    hands={ name="Nyame Gauntlets", augments={'Path: B',}},
    legs="Eri. Leg Guards +2",
    feet="Erilaz Greaves +2",
    neck="Sacro Gorget",
    waist="Sroda Belt",
    left_ear="Mendi. Earring",
    right_ear={ name="Erilaz Earring +1", augments={'System: 1 ID: 1676 Val: 0','Accuracy+12','Mag. Acc.+12','Damage taken-4%',}},
    left_ring="Eihwaz Ring",
    right_ring="Moonlight Ring",
    back={ name="Ogma's Cape", augments={'HP+60','Eva.+20 /Mag. Eva.+20','Enmity+10','Parrying rate+5%',}},
}