sets.exported={
    main="Caladbolg",
    sub="Utu Grip",
    ammo="Knobkierrie",
    head="Ratri Sallet",
    body="Ignominy Cuirass +2",
    hands="Rat. Gadlings +1",
    legs="Ratri Cuisses",
    feet="Ratri Sollerets",
    neck={ name="Abyssal Beads +1", augments={'Path: A',}},
    waist={ name="Sailfi Belt +1", augments={'Path: A',}},
    left_ear="Lugra Earring +1",
    right_ear="Thrud Earring",
    left_ring="Epaminondas's Ring",
    right_ring="Niqmaddu Ring",
    back={ name="Ankou's Mantle", augments={'STR+20','Accuracy+20 Attack+20','Weapon skill damage +10%',}},
}