sets.exported={
    main="Naegling",
    sub="Sacro Bulwark",
    ammo="Homiliary",
    head={ name="Viti. Chapeau +1", augments={'Enfeebling Magic duration','Magic Accuracy',}},
    body="Shamash Robe",
    hands="Volte Gloves",
    legs={ name="Carmine Cuisses +1", augments={'HP+80','STR+12','INT+12',}},
    feet={ name="Vitiation Boots +2", augments={'Immunobreak Chance',}},
    neck={ name="Loricate Torque +1", augments={'Path: A',}},
    waist="Sacro Cord",
    left_ear="Regal Earring",
    right_ear="Malignance Earring",
    left_ring={ name="Metamor. Ring +1", augments={'Path: A',}},
    right_ring="Kishar Ring",
    back={ name="Sucellos's Cape", augments={'MND+20','Mag. Acc+20 /Mag. Dmg.+20','"Fast Cast"+10','Damage taken-5%',}},
}