sets.exported={
    main="Daybreak",
    sub="Chanter's Shield",
    ammo="Staunch Tathlum",
    head={ name="Merlinic Hood", augments={'Mag. Acc.+22','"Fast Cast"+5','INT+6','"Mag.Atk.Bns."+13',}},
    body={ name="Viti. Tabard +2", augments={'Enhances "Chainspell" effect',}},
    hands="Volte Gloves",
    legs="Aya. Cosciales +2",
    feet={ name="Merlinic Crackows", augments={'Mag. Acc.+3','"Conserve MP"+6','CHR+9',}},
    neck="Voltsurge Torque",
    waist="Embla Sash",
    left_ear={ name="Lethargy Earring", augments={'System: 1 ID: 1676 Val: 0','Accuracy+8','Mag. Acc.+8',}},
    right_ear="Malignance Earring",
    left_ring="Kishar Ring",
    right_ring="Prolix Ring",
    back="Altruistic Cape",
}